# 기본 가타카나 46자
katakana_data = {
    'ア': {'english': 'a', 'korean': '아'},
    'イ': {'english': 'i', 'korean': '이'},
    'ウ': {'english': 'u', 'korean': '우'},
    'エ': {'english': 'e', 'korean': '에'},
    'オ': {'english': 'o', 'korean': '오'},
    'カ': {'english': 'ka', 'korean': '카'},
    'キ': {'english': 'ki', 'korean': '키'},
    'ク': {'english': 'ku', 'korean': '쿠'},
    'ケ': {'english': 'ke', 'korean': '케'},
    'コ': {'english': 'ko', 'korean': '코'},
    'サ': {'english': 'sa', 'korean': '사'},
    'シ': {'english': 'shi', 'korean': '시'},
    'ス': {'english': 'su', 'korean': '스'},
    'セ': {'english': 'se', 'korean': '세'},
    'ソ': {'english': 'so', 'korean': '소'},
    'タ': {'english': 'ta', 'korean': '타'},
    'チ': {'english': 'chi', 'korean': '치'},
    'ツ': {'english': 'tsu', 'korean': '츠'},
    'テ': {'english': 'te', 'korean': '테'},
    'ト': {'english': 'to', 'korean': '토'},
    'ナ': {'english': 'na', 'korean': '나'},
    'ニ': {'english': 'ni', 'korean': '니'},
    'ヌ': {'english': 'nu', 'korean': '누'},
    'ネ': {'english': 'ne', 'korean': '네'},
    'ノ': {'english': 'no', 'korean': '노'},
    'ハ': {'english': 'ha', 'korean': '하'},
    'ヒ': {'english': 'hi', 'korean': '히'},
    'フ': {'english': 'fu', 'korean': '후'},
    'ヘ': {'english': 'he', 'korean': '헤'},
    'ホ': {'english': 'ho', 'korean': '호'},
    'マ': {'english': 'ma', 'korean': '마'},
    'ミ': {'english': 'mi', 'korean': '미'},
    'ム': {'english': 'mu', 'korean': '무'},
    'メ': {'english': 'me', 'korean': '메'},
    'モ': {'english': 'mo', 'korean': '모'},
    'ヤ': {'english': 'ya', 'korean': '야'},
    'ユ': {'english': 'yu', 'korean': '유'},
    'ヨ': {'english': 'yo', 'korean': '요'},
    'ラ': {'english': 'ra', 'korean': '라'},
    'リ': {'english': 'ri', 'korean': '리'},
    'ル': {'english': 'ru', 'korean': '루'},
    'レ': {'english': 're', 'korean': '레'},
    'ロ': {'english': 'ro', 'korean': '로'},
    'ワ': {'english': 'wa', 'korean': '와'},
    'ヲ': {'english': 'wo', 'korean': '오'},
    'ン': {'english': 'n', 'korean': '응'}
}

# 탁음 및 반탁음
katakana_dakuten_data = {
    'ガ': {'english': 'ga', 'korean': '가'},
    'ギ': {'english': 'gi', 'korean': '기'},
    'グ': {'english': 'gu', 'korean': '구'},
    'ゲ': {'english': 'ge', 'korean': '게'},
    'ゴ': {'english': 'go', 'korean': '고'},
    'ザ': {'english': 'za', 'korean': '자'},
    'ジ': {'english': 'ji', 'korean': '지'},
    'ズ': {'english': 'zu', 'korean': '즈'},
    'ゼ': {'english': 'ze', 'korean': '제'},
    'ゾ': {'english': 'zo', 'korean': '조'},
    'ダ': {'english': 'da', 'korean': '다'},
    'ヂ': {'english': 'ji', 'korean': '지'},
    'ヅ': {'english': 'zu', 'korean': '즈'},
    'デ': {'english': 'de', 'korean': '데'},
    'ド': {'english': 'do', 'korean': '도'},
    'バ': {'english': 'ba', 'korean': '바'},
    'ビ': {'english': 'bi', 'korean': '비'},
    'ブ': {'english': 'bu', 'korean': '부'},
    'ベ': {'english': 'be', 'korean': '베'},
    'ボ': {'english': 'bo', 'korean': '보'},
    'パ': {'english': 'pa', 'korean': '파'},
    'ピ': {'english': 'pi', 'korean': '피'},
    'プ': {'english': 'pu', 'korean': '푸'},
    'ペ': {'english': 'pe', 'korean': '페'},
    'ポ': {'english': 'po', 'korean': '포'}
}

# 요음
katakana_yo_on_data = {
    'キャ': {'english': 'kya', 'korean': '캬'},
    'キュ': {'english': 'kyu', 'korean': '큐'},
    'キョ': {'english': 'kyo', 'korean': '쿄'},
    'シャ': {'english': 'sha', 'korean': '샤'},
    'シュ': {'english': 'shu', 'korean': '슈'},
    'ショ': {'english': 'sho', 'korean': '쇼'},
    'チャ': {'english': 'cha', 'korean': '챠'},
    'チュ': {'english': 'chu', 'korean': '츄'},
    'チョ': {'english': 'cho', 'korean': '쵸'},
    'ニャ': {'english': 'nya', 'korean': '냐'},
    'ニュ': {'english': 'nyu', 'korean': '뉴'},
    'ニョ': {'english': 'nyo', 'korean': '뇨'},
    'ヒャ': {'english': 'hya', 'korean': '햐'},
    'ヒュ': {'english': 'hyu', 'korean': '휴'},
    'ヒョ': {'english': 'hyo', 'korean': '효'},
    'ミャ': {'english': 'mya', 'korean': '먀'},
    'ミュ': {'english': 'myu', 'korean': '뮤'},
    'ミョ': {'english': 'myo', 'korean': '묘'},
    'リャ': {'english': 'rya', 'korean': '랴'},
    'リュ': {'english': 'ryu', 'korean': '류'},
    'リョ': {'english': 'ryo', 'korean': '료'},
    'ギャ': {'english': 'gya', 'korean': '갸'},
    'ギュ': {'english': 'gyu', 'korean': '규'},
    'ギョ': {'english': 'gyo', 'korean': '교'},
    'ジャ': {'english': 'ja', 'korean': '쟈'},
    'ジュ': {'english': 'ju', 'korean': '쥬'},
    'ジョ': {'english': 'jo', 'korean': '죠'},
    'ヂャ': {'english': 'ja', 'korean': '쟈'},
    'ヂュ': {'english': 'ju', 'korean': '쥬'},
    'ヂョ': {'english': 'jo', 'korean': '죠'},
    'ビャ': {'english': 'bya', 'korean': '뱌'},
    'ビュ': {'english': 'byu', 'korean': '뷰'},
    'ビョ': {'english': 'byo', 'korean': '뵤'},
    'ピャ': {'english': 'pya', 'korean': '퍄'},
    'ピュ': {'english': 'pyu', 'korean': '퓨'},
    'ピョ': {'english': 'pyo', 'korean': '표'}
}

# 촉음
katakana_soku_on_data = {
    'ッ': {'english': 'っ', 'korean': '작은 츠'}
}

